const players = 
[{
    "id": 1,
    "name": "Mel",
    "image": "https://i.ibb.co/KKyZYYr/New-Project.png",
    "salary": 86397
  }, {
    "id": 2,
    "name": "Coleen",
    "image": "https://i.ibb.co/GP6kKgm/New-Project-1.png",
    "salary": 91019
  }, {
    "id": 3,
    "name": "Renaud",
    "image": "https://i.ibb.co/fMg23fS/New-Project-2.png",
    "salary": 72738
  }, {
    "id": 4,
    "name": "Hagen",
    "image": "https://i.ibb.co/gJRhr4p/New-Project-4.png",
    "salary": 74259
  }, {
    "id": 5,
    "name": "Willamina",
    "image": "https://i.ibb.co/XbyTKfS/New-Project-3.png",
    "salary": 119365
  }, {
    "id": 6,
    "name": "Dennis",
    "image": "https://i.ibb.co/VpmBVQz/New-Project-5.png",
    "salary": 87912
  }, {
    "id": 7,
    "name": "Corinne",
    "image": "https://i.ibb.co/3r1XrFG/New-Project-6.png",
    "salary": 100538
  }, {
    "id": 8,
    "name": "Maynord",
    "image": "https://i.ibb.co/5LXh48M/New-Project-7.png",
    "salary": 89236
  }, {
    "id": 9,
    "name": "Camila",
    "image": "https://i.ibb.co/CnBz0WR/New-Project-8.png",
    "salary": 95760
  }, {
    "id": 10,
    "name": "Aviva",
    "image": "https://i.ibb.co/yS5fGmK/New-Project-5.png",
    "salary": 85996
  }, {
    "id": 11,
    "name": "Griswold",
    "image": "https://dummyimage.com/200x200.jpg/ff4444/ffffff",
    "salary": 118082
  }, {
    "id": 12,
    "name": "Sonnie",
    "image": "https://dummyimage.com/200x200.jpg/ff4444/ffffff",
    "salary": 92677
  }, {
    "id": 13,
    "name": "Randee",
    "image": "https://dummyimage.com/200x200.jpg/ff4444/ffffff",
    "salary": 113824
  }, {
    "id": 14,
    "name": "Kennie",
    "image": "https://dummyimage.com/200x200.jpg/ff4444/ffffff",
    "salary": 96176
  }, {
    "id": 15,
    "name": "Jonas",
    "image": "https://dummyimage.com/200x200.jpg/ff4444/ffffff",
    "salary": 82519
  }]

  export default players;